services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-studio
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      GEMINI_API_KEY: ${GEMINI_API_KEY}   # definilo en un .env del host o en tu orquestador
