services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: ai-studio-dev
    ports:
      - "5173:5173"
    environment:
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
    volumes:
      - .:/app:cached
      - node-modules:/app/node_modules
    command: ["npm","run","dev"]

volumes:
  node-modules:
